### ISSUE TITLE
Access the Request IP?

### ISSUE THREAD

**Issue by blaineam** [swhitty/FlyingFox#106]
Any way to make the IP Address of the requester available in the HTTPRequest or HTTPHandler blocks? I see it logged when the connection closes but cannot figure out how to access it from a HTTPHandler.

**Comment by swhitty** [comment]
Yes this is something I have been intending on adding for a while — thanks for the reminder, https://github.com/swhitty/FlyingFox/pull/107 now adds it

**Comment by swhitty** [comment]
available in latest release [0.16.0](https://github.com/swhitty/FlyingFox/releases/tag/0.16.0)
