### ISSUE TITLE
Error when targeting macOS 12.0

### ISSUE THREAD

**Issue by stackotter** [swhitty/FlyingFox#23]
Hi Simon,

I'm running into an issue with FlyingFox when building my project. The problem only arises when I specifically direct Swift to build it for macOS 12.0 (the reason I'm doing that is because I'm installing my tool through mint, which automatically targets the machine's os version). Here's the error:

```console
$ swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx12.0
Building for production...
/Users/stackotter/Desktop/Projects/Swift/Scute/.build/checkouts/FlyingFox/Sources/Handlers/ProxyHTTPHandler.swift:51:42: error: ambiguous use of 'data'
        let (data, response) = try await session.data(for: req)
                                         ^
/Users/stackotter/Desktop/Projects/Swift/Scute/.build/checkouts/FlyingFox/Sources/URLSession+Async.swift:42:10: note: found this candidate
    func data(for request: URLRequest, forceFallback: Bool = false) async throws -> (Data, URLResponse) {
         ^
Foundation.URLSession:3:17: note: found this candidate
    public func data(for request: URLRequest, delegate: URLSessionTaskDelegate? = nil) async throws -> (Data, URLResponse)
                ^
[3/7] Compiling FlyingFox AsyncSequence+Extensions.swift
```

It seems like you may have to rename your method or change the function signature in some other way so that it doesn't clash with the macOS 12.0 API additions,

Cheers,
stackotter

**Comment by swhitty** [comment]
Thanks for reporting this @stackotter. 🙏🏻

I have renamed the method on the `main` branch.

I have tested with the [example CLI app](https://github.com/swhitty/FlyingFoxCLI) and it now works;
```
% mint install swhitty/FlyingFoxCLI@main
```

**Comment by stackotter** [comment]
Awesome, thanks 👍
