### ISSUE TITLE
Does it have TLS/SSL support?

### ISSUE THREAD

**Issue by ConsoleTVs** [swhitty/FlyingFox#34]
Althought we can use nginx/apache with a SSL certificate I am wondering if there are plans to add it here in the future.

**Comment by swhitty** [comment]
There are no plans for TLS support. The only real stated goal of FlyingFox is;

> Lightweight, HTTP server written in Swift using async/await.

Expanding on this we want 0 dependencies and fast compilation which really prevents any TLS on the roadmap.  That said I have deployed FlyingFox to Google Cloud Run which then runs behind a TLS reverse proxy see [here](https://github.com/swhitty/FlyingFoxCLI).
