### ISSUE TITLE
File Uploads

### ISSUE THREAD

**Issue by omrd** [swhitty/FlyingFox#48]
Is FlyingFox able to handle large file uploads?

**Comment by swhitty** [comment]
Currently not as [`HTTPRequest`](https://github.com/swhitty/FlyingFox/blob/main/FlyingFox/Sources/HTTPRequest.swift) includes `var body: Data` so it requires the body to exist completely within memory.

I suppose we could change that so the body is represented as `some AsyncSequence<UInt8>` and then handlers of `multipart/form-data` could transform that into a sequence of parts delimited by the boundaries so the upload file could be processed as a stream.

**Comment by omrd** [comment]
Would be pretty awesome to have (my app handles medical imaging and I normally deal with files that can go up to 2GB).

**Comment by swhitty** [comment]
How are you uploading these images?

Posting the file as the HTTP body? 
`% curl --data '@<filename>' http://server/upload`

Or within `multipart/form-data`
`curl -F 'payload=@<filename>' http://server/upload`

We could probably support the first case quite quickly, while the 2nd requires parsing of the form parts and data.

**Comment by omrd** [comment]
On the client side it's just plain javascript xhr upload (with whatever web browser they use).
```JS
xhr.open('POST', this.url, true);
xhr.setRequestHeader('Content-Type', "application/octet-stream"); //set content type to stream.
xhr.send(file); //upload
```

On the server side, I get the upload in chunks which I use a FileHandler to write to disk. So it would be something similar to this.

```swift
let handler: FileHandler = .init(......)

for await chunk in request.stream { data, error? in 

    guard error == nil else {  /* do error handling here if the stream cuts off */ }

    handler.seekEndOfFile() ....
    handler.write(data).... 
}
```


This is nice to have although I propose going even a step further and abstracting further out by allowing something like above or a built in method where I can do something like this.


```swift
let (result, fileULR) = await request.getFullStream()

if result == .succeed { /* do success processing here */ }
else { /* do failure processing here */ }
```

**Comment by swhitty** [comment]
OK great this should post the file as a the HTTP body like;
`% curl --data '@<filename>' http://server/upload`

I have had a look at supporting this and it does mean a breaking change as `HTTPRequest` would then need an `async` body property and is then unable to fulfil `Equatable` conformance.

I will need to think about it more and possibly add a `HTTPRequestAsync` with `HTTPHandlerAsync` or the like.

**Comment by swhitty** [comment]
Version [0.11.0](https://github.com/swhitty/FlyingFox/releases/tag/0.11.0) adds support for very large request and responses.

Requests now include a `bodySequence: HTTPBodySequence` which allows the request body to be iterated in small chunks as the arrive:
```swift
func saveBody(request: HTTPRequest) async throws -> HTTPResponse {
  let file =  URL(fileURLWithPath: "/tmp/file")
  _ = FileManager.default.createFile(atPath: file.path, contents: nil)
  let handle = try FileHandle(forWritingTo: file)
  for try await chunk in req.bodySequence {
    try handle.write(contentsOf: chunk)
  }
  return HTTPResponse(statusCode: .ok)
}
```

**Comment by omrd** [comment]
Awesome, thank you will do some testing on this.

**Comment by swhitty** [comment]
Are you uploading as `multipart/form-data` ?
`% curl -F 'payload=@<filename>' http://server/upload`

FlyingFox currently does not include a parser for bodies in this format:

```
Content-Type: multipart/form-data; boundary=---WebKitFormBoundary7MA4YWxkTrZu0gW

-----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=”file”; filename=”file.txt”
Content-Type: plain/text

XXXXXXXXXXXXXXXXXX
-----WebKitFormBoundary7MA4YWxkTrZu0gW--
```

If you upload using `XMLHTTPRequest` you may be able to place the filename in another header.

```
xhr.open('POST', this.url, true);
xhr.setRequestHeader('Content-Type', "application/octet-stream"); //set content type to stream.
xhr.setRequestHeader('Filename', file.name); 
xhr.send(file); //upload
```

**Comment by fdddf** [comment]
> Are you uploading as `multipart/form-data` ? `% curl -F 'payload=@<filename>' http://server/upload`
> 
> FlyingFox currently does not include a parser for bodies in this format:
> 
> ```
> Content-Type: multipart/form-data; boundary=---WebKitFormBoundary7MA4YWxkTrZu0gW
> 
> -----WebKitFormBoundary7MA4YWxkTrZu0gW
> Content-Disposition: form-data; name=”file”; filename=”file.txt”
> Content-Type: plain/text
> 
> XXXXXXXXXXXXXXXXXX
> -----WebKitFormBoundary7MA4YWxkTrZu0gW--
> ```
> 
> If you upload using `XMLHTTPRequest` you may be able to place the filename in another header.
> 
> ```
> xhr.open('POST', this.url, true);
> xhr.setRequestHeader('Content-Type', "application/octet-stream"); //set content type to stream.
> xhr.setRequestHeader('Filename', file.name); 
> xhr.send(file); //upload
> ```
> 
> And [read like this](https://github.com/swhitty/FlyingFox/issues/48#issuecomment-1493485243).

@swhitty Got it, thanks for your reply, I will try to use xhr to send request instead.
