### ISSUE TITLE
isRunning: Ability to see if the server instance is currently running or not.

### ISSUE THREAD

**Issue by Aayush9029** [swhitty/FlyingFox#58]
Hi! First of all, You've done an amazing job with this library. Thank you very much.

I was wondering if there's a cleaner way to see if `HTTPServer` is active or not. Current work around seems to be either using a custom wrapper around `HTTPServer` or use `self.listeningAddress != nil`.

Let me know what you think

**Comment by swhitty** [comment]
Thank you 🙏🏻

There is currently an internal [`HTTPServer.isListening`](https://github.com/swhitty/FlyingFox/blob/4f7e628e844476450b2aa650b4df164cde33d77f/FlyingFox/Sources/HTTPServer.swift#L95) property that I could make public?

This will be `true` when the server is running and currently listening on the listening Address.
