### ISSUE TITLE
Abilities to insert or delete the handlers in RoutedHTTPHandler

### ISSUE THREAD

**Issue by timyeou1234** [swhitty/FlyingFox#77]
We currently only support for 
```
public mutating func appendRoute(_ route: HTTPRoute, to handler: HTTPHandler) {
        handlers.append((route, handler))
    }
```

```
    public mutating func appendRoute(_ route: HTTPRoute,
                                     handler: @Sendable @escaping (HTTPRequest) async throws -> HTTPResponse) {
        handlers.append((route, ClosureHTTPHandler(handler)))
    }
```
  Can we also have the function that inserts at 0 or remove all handlers.
  The scenario we encounter is that we use it on the UI test, while we need to mock a response change, we will need to change the handlers array to make it happen, if append is the only function, we will need to rebuild a server again to make the change.

**Comment by swhitty** [comment]
Great suggestion @timyeou1234 🙏🏻

`insertRoute(_, at: to:)` has been added along with conformance to [`RangeReplaceableCollection`](https://developer.apple.com/documentation/swift/rangereplaceablecollection) which provides many more methods that may be useful.
