### ISSUE TITLE
How would I use this library to stream a large file chunk by chunk?

### ISSUE THREAD

**Issue by blaineam** [swhitty/FlyingFox#92]
I have a use case where I decrypt large (4-8GB) video files on device and want to allow the decrypted media to be written to the client chunk by chunk so that the app does not exhaust available memory. Is that possible with this library to say have an http handler tied to a route that lets you write to the client chunk by chunk and then close the connection when finished? I see the FlyingSocks looks like it might allow that but Im not sure how to use that with a HTTPHandler tied to the web server.

Im hoping it would be possible because the library I'm using presently does not allow streaming to the http client piece by piece unfortunately.

**Comment by swhitty** [comment]
Yes support for[ large file uploads](https://github.com/swhitty/FlyingFox/issues/48) was added in version [0.11.0](https://github.com/swhitty/FlyingFox/releases/tag/0.11.0)

`HTTPRequest` includes `bodySequence` which can be integrated in chunks like so;

```swift
func saveBody(request: HTTPRequest) async throws -> HTTPResponse {
  let file = URL(fileURLWithPath: "/tmp/file")
  _ = FileManager.default.createFile(atPath: file.path, contents: nil)
  let handle = try FileHandle(forWritingTo: file)
  for try await chunk in req.bodySequence {
    try handle.write(contentsOf: chunk)
  }
  return HTTPResponse(statusCode: .ok)
}
```

If the uploaded data is within a multipart form you will need to parse that yourself.  There is a wip branch [multipartform](https://github.com/swhitty/FlyingFox/compare/main...multipartform) which seeks to provide an async parser, but there is no eta for its completion.

**Comment by blaineam** [comment]
Yeah I saw the uploads but this is more for responding to the http client in chunks, not parsing the request in chunks. Think of streaming a large video file in chunks vs uploading a large file to the server. It's the opposite direction.

Equivalent would be like reading a file line by line from a server to the client/user and then when the file is fully sent to the client the application closes the connection.

I need Server > Client in chunks vs. Client > Server in Chunks.

Is that possible to do with this library?

So Ideally if I setup a GET Route "/media/*" and I want to have it check if the requested path exists, decrypt it using a set key, and then start streaming the decrypted chunks as it decrypts them setting the appropriate headers to begin with such as Content-Type and Content-Length. 

I have code that can output the decrypted chunks piece by piece I just don't have a web server in swift that can let me immediately send each of those chunks to the http client in chunks to avoid OOM issues.

Does that explain things better?

**Comment by swhitty** [comment]
I am following now — _making_ HTTP requests as a client....

The critical methods [`HTTPEncoder.encodeRequest`](https://github.com/swhitty/FlyingFox/blob/53ee852a959be049f6bf513dc107286f1c4be741/FlyingFox/Sources/HTTPEncoder.swift#L85) and [`HTTPDecoder.decodeResponse`](https://github.com/swhitty/FlyingFox/blob/53ee852a959be049f6bf513dc107286f1c4be741/FlyingFox/Sources/HTTPDecoder.swift#L63) are not available publicly but I have [added](https://github.com/swhitty/FlyingFox/pull/93) a private (not really supported) `HTTPClient` that you can try out on the `main` branch:

For example, if a server was running on `localhost:8080`, its possible to send a `HTTPRequest` and receive a `HTTPResponse`

```swift
@_spi(Private) import struct FlyingFox._HTTPClient

let client = _HTTPClient()
let response = try await client.sendHTTPRequest(HTTPRequest(path: "/hello"), to: .loopback(port: 8080))
```

There are some limitations to this (which is why its private)

-  Requests need to be made to IP addresses, so you need to lookup this yourself
-  `HTTPHeader.host` will need to be manually populated with the dns name
- SSL is not supported

There are some alternatives you could try:
- [`URLSessionDataTask`](https://developer.apple.com/documentation/foundation/urlsessiondatatask)
- [swift-server/async-http-client](https://github.com/swift-server/async-http-client)

**Comment by blaineam** [comment]
I guess I'm even more confused now...

I'm not needing to make http calls to another server to download files chunk by chunk, although that's cool that you could do that even if unsupported. 

With my iOS app creating a web/http server to serve a site in a directory on the iPhone, I want to be able to let the app process the files from that directory decrypting them and serving the decrypted chunks piece by piece so that the web server doesn't have to buffer an 8GB decrypted video file into memory before sending it to the other browser or device accessing the decrypted files. 

Basically the app would decrypt say 8KB at a time and I want to be able to immediately send that to the http client requesting the file and I want to send the binary data to the client browser as it is available allowing for more optimal memory footprints since only a single 8KB chunk would be in memory at a time as opposed to the full 8GB file. 

So I'd imagine it would consist of the server allowing me to make multiple calls to write to the http response. 

So client makes a request to the app. The app keeps the connection open until I make a call to close it. While the connection with the client is open I could call something like writeResponse(data:...) as many times as I need to as I'm decrypting each chunk and then I can call something like CloseResponse() and it would end the connection because the server in the app has fulfilled the request. 

In PHP it would be something akin to:
<?php

echo "part 1";
usleep(1000);
echo "part 2";
die();

?>

and that would immediately show "part 1" in the web browser and the web browser would keep the connection open for another second or so and then the web browser would show "part 2" after "part 1" and then the browser would stop showing the page is still loading. 

I want to be able to achieve something like that with swift where the connection stays open to the browser until I send all the data to the web browser from a swift web server and manually close the connection. The main part being sending the output over the connection piece by piece. 


Sorry for the long explanation but I feel I haven't been explaining my intent well enough so I hope this clarifies it better.

**Comment by swhitty** [comment]
Yes support for this was added in https://github.com/swhitty/FlyingFox/pull/57 😸

It should like you will just need to conform your data to `AsyncChunkedSequence`, e.g.:

```swift
struct FileEncryptor: AsyncChunkedSequence {
    typealias Element = UInt8

    let url: URL

    func makeAsyncIterator() -> AsyncIterator {
        try! AsyncIterator(handle: FileHandle(forReadingFrom: url))
    }

    struct AsyncIterator: AsyncChunkedIteratorProtocol {
        typealias Element = UInt8

        let handle: FileHandle

        /// Retrieves n elements from sequence in a single array.
        /// - Returns: Array with the number of elements that was requested. Or Nil.
        mutating func nextChunk(count: Int) async throws -> [UInt8]? {
            try handle.read(upToCount: count).map { Array($0) }
        }
        
        mutating func next() async throws -> UInt8? {
           try handle.read(upToCount: 1).map { $0.first! }
        }
    }
}
```

Then you can return that in any response, the size needs to be noted up front;

```swift
HTTPResponse(
  statusCode: .ok,
  body: HTTPBodySequence(from: FileEncryptor(url: file), count: 1024)
)
```

**Comment by blaineam** [comment]
Was able to make the transition from Telegraph to FlyingFox in a couple hours and now my app is so much more performant in decrypting large media files. Thank You!

In case it helps the next person:
The calls to nextChunk can be any arbitrary byte count so you cannot read line by line but need to buffer the overflow of bytes as you read each decrypted line.

HTTPBodySequence count needs to be the exact number of bytes you will return so be sure you are calculating that number exactly rather than an estimate.

Thanks for your help in pointing out how to send large files to the http client in pieces.

**Comment by swhitty** [comment]
Great, did you need to process (encrypt/decrypt)? the chunks server side before sending them?

We may be able to make some improvements here allowing implementations to return less than and automatically buffer for you.

```swift
// try and return the requested number of bytes if possible. Returning less would result in another call in the future for the remaining...
mutating func nextChunk(max numberOfBytes: Int) async throws -> [UInt8]?
```

**Comment by blaineam** [comment]
Yeah returning less might work but what if the decryption chunks are larger. 

I solved it rather easily. 

I added a buffer variable to the AsyncIterator Struct. 

I use that variable to set the start of the decrypted chunk and then I while loop decrypting chunks until the decrypted chunks are greater than or equal to the requested chunk size and then I split the decrypted chunks to the requested chunk length and was able to set the new buffer value and then return the requested chunk. 

It wasn't too hard to draft up that algorithm thankfully once I understood how it was going to be called. 

The main issue I had was I would set Content-Length headers based on a "rough" estimate rather than a precise size the decrypted file would occupy. 

This required me to fix the decrypted size calculations to actually be exact and I could have avoided an algorithm all together by just storing the original size in the encrypted files themselves but I already have too many files already encrypted to adjust that algorithm so I just opted for a simple decrypt the first full length chunk, count chunks to last chunk, add those to the length of the final chunk that could and likely is less than the first chunk length. So unfortunately my approach has to read the file twice once to get the size of the decrypted file and once to fully decrypt every chunk. 

This is still far more performant with my app though by allowing the browser to receive the decrypted data as soon as possible so video playback can occur immediately while it is downloading the rest of the video. 

For context my size estimation was really close but on a 300MB file it was 1.5MB off so not perfect. 

The estimation can cause other issues though so being exact actually improves reliability.

**Comment by swhitty** [comment]
Thanks for your feedback @blaineam I have made some recent changes on main which will be included in the next release which may help here.

### AsyncBufferedSequence
`AsyncChunkedSequence` has been deprecated and replaced with `AsyncBufferedSequence` https://github.com/swhitty/FlyingFox/pull/95

The new sequence works similarly but the iterator is now permitted to return _less_ elements than those that were requested, returning `nil` when the sequence has completed.

```
/// Retrieves available elements from the buffer. Suspends if 0 elements are available.
/// - Parameter count: The maximum number of elements to return
/// - Returns: Array with between 1 and the number elements that was requested. Nil is returned if the sequence has ended.
mutating func nextBuffer(atMost count: Int) async throws -> Buffer?
```

### Transfer-Encoding: chunked
HTTPResponse can omit `Content-Length` and use `Transfer-Encoding: chunked` when the final size of the body is not known up front. https://github.com/swhitty/FlyingFox/pull/97.

This encoding is automatically used when `HTTPBodySequence` is not supplied with a count:

```swift
let fileLoadSequence: some AsyncBufferedSequence<UInt8> = ....

HTTPResponse(
   statusCode: .ok,
   body: HTTPBodySequence(from: fileLoaderSequence)
)
```

> Note: requires Swift 5.9 and later

**Comment by blaineam** [comment]
Not exactly working reliably for me.
 Im getting a lot of messages like: 
``` error: SocketError. Write(54): Connection reset by peer```

Sometimes it works and other times it doesn't and it's not consistent but a lot of times I get that message where I wasn't getting that previously.

**Comment by swhitty** [comment]
Maybe the HTTP client is hanging up the socked because the chunked encoding is invalid?

Is netcat able to retrieve the full body? (It won't validate anything)

```
$ nc localhost
GET /file HTTP/1.1

HTTP/1.1 200 OK\r
Transfer-Encoding: chunked\r
\r
0A\r
Hello Worl\r
02\r
d!\r
0\r
\r
```

**Comment by blaineam** [comment]
I was able to fix some stability issues by re-adding the overflow buffer for when the decrypted chunk is larger than the atMost of your protocol method. This could be remedied if I could be in control of what size is requested for the atMost count parameter or if it would be larger than 8192 consistently I might have more luck. It has made images far faster at rendering. I am unable to use Transfer-Encoding: chunked for video files as Safari does not allow anything without a valid Content-Length unfortunately. I do see that omitting the count when returning the response, there is an additional header (Transfer-Encoding: Identity) that cannot be overwritten by setting the .transferEncoding: "chunked" header. That may be causing safari to have issues with video files Im not sure. Using count for the video files seems to be mostly operational at least.

**Comment by swhitty** [comment]
Interesting, because FlyingFox represents headers as `[HTTPHeader: String]` we cannot return the same header twice, but HTTP allows for a common delimited list of values for repeated headers, so I may be able to detect this and append the chunked here here;

```
Transfer-Encoding: Identity, chunked
```

Thinking about it more, it may be more useful if the buffer had a "suggested" size allowing implementations to return over or under.  It shouldn't really matter as we are waiting for `nil` to indicate termination.....

```swift
 mutating func nextBuffer(suggested count: Int) async throws -> Buffer?
```

**Comment by blaineam** [comment]
So overflow buffer is not needed, I just have to set the count when returning the response but only for mp4 video files. This does seem even more performant overall

I like the suggested size idea definitely more flexible overall.

**Comment by swhitty** [comment]
Great I have made some more changes that may or may not be of use:

`AsyncBufferedSequence` is now requesting a "suggested" size of the buffer https://github.com/swhitty/FlyingFox/pull/100
```swift
mutating func nextBuffer(suggested count: Int) async throws -> Buffer?
```

Requests / Responses now support multiple values for a single header so it should be possible to set `Transfer-Encoding: Identity` and then the server will automatically append `, chunked`.  https://github.com/swhitty/FlyingFox/pull/99

And `HTTPBodySequence` now has a public exposes the suggested buffer size, so you can specify larger values

```swift
HTTPResponse(
   statusCode: .ok,
   body: HTTPBodySequence(from: fileLoaderSequence, count: fileSize, suggestedBufferSize: 8192)
)
```

**Comment by blaineam** [comment]
Update is working quite nicely, Thank You!
