### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by noahsmartin** [swhitty/FlyingFox#96]
I noticed the Package.swift does not support watchOS, but the code seems to build without a problem on watchOS, this commit adds it and the result worked fine at least for how I was using it: https://github.com/EmergeTools/FlyingFox/commit/30a96b49f55762750899a4b8ea68301e32b9c112

I didn't test all features, just the ones I'm using for SnapshotPreviews here: https://github.com/EmergeTools/SnapshotPreviews-iOS/blob/main/Sources/SnapshottingSwift/Snapshots.swift

Is support for this something the maintainers would be interested in adding?

**Comment by swhitty** [comment]
Great idea @noahsmartin — happy to add this.

I have added this to the Package.swift in https://github.com/swhitty/FlyingFox/pull/98.
